export const DashboardType = {
  TEST: 'TEST'
};

export const ChatBotType = {
  INCHAT: 'INCHAT',
  OUTCHAT: 'OUTCHAT'
};

export const LoginType = {
  AUTHENTICATE: 'AUTHENTICATE'
};

export const ErrorType = {
  ERROR_LOG: 'ERROR_LOG'
};

export const EmployeeType = {
  UPDATE_EMPLOYEE_DATA: 'UPDATE_EMPLOYEE_DATA',
  SET_NEW_EMPLOYEE: 'SET_NEW_EMPLOYEE',
  MODIFY_HIRE_DATE: 'MODIFY_HIRE_DATE',
  GET_CURRENT_EMPLOYEE: 'GET_CURRENT_EMPLOYEE',
  UPDATE_COMPANY_DATA: 'UPDATE_COMPANY_DATA',
  UPDATE_EVENT_REASON_DATA: 'UPDATE_EVENT_REASON_DATA',
  MODIFY_DOB: 'MODIFY_DOB',
  UPDATE_COUNTRY_OF_BIRTH: 'UPDATE_COUNTRY_OF_BIRTH',
  MODIFY_DATEOFDEATH: 'MODIFY_DATEOFDEATH',
  MODIFY_CERTIFICATE_START_DATE: 'MODIFY_CERTIFICATE_START_DATE',
  MODIFY_CERTIFICATE_END_DATE: 'MODIFY_CERTIFICATE_END_DATE'
};

